# Fonts: Iosevka Term, FiraCode Nerd Font Mono

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"

[hg_branch]
symbol = "î‚ "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "î‚  "
style = "fg:bright-purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
ignore_submodules = true
untracked = ""

[package]
format = "[$symbol$version]($style) "
symbol = "ï£– "
style = "208"

[cmd_duration]
format = "ï™ [$duration]($style) "
style = "yellow"

[directory]
read_only = " ï ½"
truncate_to_repo = false

[battery]
disabled = true

[aws]
symbol = "îŒ½  "

[bun]
format = "[$symbol($version )]($style)"

[buf]
format = "[$symbol($version )]($style)"
symbol = "ï’ "

[c]
format = "[$symbol($version )]($style)"
symbol = "î˜ "
style = "149"

[cmake]
format = "[$symbol($version )]($style)"
style = "blue"

[cobol]
format = "[$symbol($version )]($style)"
style = "blue"

[conda]
symbol = "ï„Œ "
style = "green"

[crystal]
format = "[$symbol($version )]($style)"

[daml]
format = "[$symbol($version )]($style)"

[dart]
format = "[$symbol($version )]($style)"
symbol = "î˜ "
style = "blue"

[deno]
format = "[$symbol($version )]($style)"

[docker_context]
symbol = "ïŒˆ "
format = '[$symbol$context]($style) '

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
format = '[$symbol($version )]($style)'
symbol = "î‰µ "
style = "purple"

[elm]
format = '[$symbol($version )]($style)'
symbol = "î˜¬ "

[erlang]
format = '[$symbol($version )]($style)'

[golang]
format = '[$symbol($version )]($style)'
symbol = "î˜§ "
style = "cyan"

[haskell]
symbol = "î· "
style = "purple"

[helm]
format = '[$symbol($version )]($style)'
style = "white"

[java]
format = '[$symbol($version )]($style)'
symbol = "î‰– "
style = "red"

[julia]
format = '[$symbol($version )]($style)'
symbol = "î˜¤ "
style = "purple"

[kotlin]
format = '[$symbol($version )]($style)'
style = "blue"

[lua]
format = '[$symbol($version )]($style)'
symbol = "\ue620 "

[nim]
format = '[$symbol($version )]($style)'
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
format = '[$symbol($version )]($style)'
symbol = "îœ˜ "
style = "green"

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[perl]
format = '[$symbol($version )]($style)'
style = "149"

[php]
format = '[$symbol($version )]($style)'
style = "147"

[pulumi]
format = '[$symbol$stack]($style)'

[purescript]
format = '[$symbol($version )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "îˆµ "
style = "bright-yellow"

[raku]
format = '[$symbol($version )]($style)'

[red]
format = '[$symbol($version )]($style)'

[rlang]
format = '[$symbol($version )]($style)'

[ruby]
format = '[$symbol($version )]($style)'
style = "red"

[rust]
format = '[$symbol($version )]($style)'
symbol = "î¨ "
style = "red"

[spack]
format = '[$symbol($version )]($style)'
symbol = "ğŸ…¢ "

[swift]
format = '[$symbol($version )]($style)'
style = "202"

[vagrant]
format = '[$symbol($version )]($style)'

[vlang]
format = '[$symbol($version )]($style)'

[zig]
format = '[$symbol($version )]($style)'
symbol = "î¨ "
