
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode       = "size"
ratio          = [2,4,3]
scrolloff      = 3
title_format   = "ðŸ“‚ {cwd}"
format = "{icon} {name}"

show_symlink = true
#sort_by = "natural"
sort_dir_first = true

[preview]
max_width       = 1200
max_height      = 1080

